// swift-format-ignore-file: AlwaysUseLowerCamelCase
// SRP fixtures use single-letter uppercase names (B, M1, K) to match the
// notation in SRP.swift, RFC 5054, and pyatv's hap_srp.py.

import BigInt
import Crypto
import Foundation
import Testing

@testable import SwiftATV

/// Tests for the HAP pair-setup state machine.
///
/// End-to-end pair-setup requires a real Apple TV displaying a PIN, so the
/// M4/M5/M6 round-trip is exercised manually during pairing. These tests
/// cover the pieces that can be verified offline:
/// - M1 TLV format
/// - M3 TLV output using a canned M2 response + a deterministic SRP key
///   (verifies byte-level interop with pyatv/srptools)
/// - Error TLV in any response surfaces as `ATVError.authenticationFailed`
/// - Credentials surfaced by `finish` has the right shape after a successful
///   M6 exchange (tested by feeding a hand-constructed M6 built with known
///   accessory keys)
@Suite("HAP pair-setup state machine")
struct HAPPairSetupTests {

    // MARK: - Shared fixture data

    /// The same client private 'a' used by SRPTests for the pyatv vector.
    private static let clientPrivateA = BigUInt(
        "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
        radix: 16
    )!

    private static let clientID = Data("11111111-2222-3333-4444-555555555555".utf8)

    private static let pin = "1234"

    /// M2 TLV (state=2, salt, publicKey=B) — bytes generated by Python
    /// script using the same (salt, B) from SRPTests.
    private static let m2TLVHex: String = {
        let salt = "830a04e00070c46978c6b05b7c67f545"
        let B =
            "c7f4f55c10d0abbc303dfbbe8ac2b12f2522e3e3d038bc9c196d910c7ad19b76"
            + "da8755093b3f1c3352f6896493b924ba4c4f300721079225dcc0b7ded37750e2"
            + "8e57ccf1a26f09042abb9c087c7f8d48babe1c307fc745244ba71df5289bf359"
            + "ab1ebd135e5af837800bd09e70a0da8fda8e835c9edd52af59981d77d2f323b3"
            + "252d2d5226269685c9af791fe260506222281905c87a2010deda12b528a378d6"
            + "b1df7e0fd51a70ca309c047a48232728beafa91413451974d5ac18bb55fba5a5"
            + "a6bf15f35b161569bab7d7c719a17b937a8e9bbdf273f47006dbcfffa571ad3a"
            + "27e706d860de7e79c264e065aa4b84f0f89c7dc6c1991db7bebc3d86bc7895b4"
            + "2d507e3427385fa247208bc1e3f6444f3915a787470afd743d866f9704bb82c9"
            + "03d94a8b6e2679f2ed1796f125839b63cf261739465f4ff28974fdc343de8b8d"
            + "2a391fb093e6131551409e9e3e1ae76c33b439de1f775a9f7c6e9d72ae319b81"
            + "b2eabaec21e2ba59388f28ca55d9f13d59bb2b5ff68f14ed03ce1dc425683e9a"
        // Build TLV: state=2, salt (0x02), publicKey (0x03)
        var data = Data([0x06, 0x01, 0x02])  // state=2
        data.append(0x02)  // salt tag
        data.append(UInt8(salt.count / 2))
        data.append(
            contentsOf: stride(from: 0, to: salt.count, by: 2).map {
                UInt8(
                    salt[salt.index(salt.startIndex, offsetBy: $0)..<salt.index(salt.startIndex, offsetBy: $0 + 2)],
                    radix: 16)!
            })
        // publicKey: B is 384 bytes → two 255-byte chunks (255 + 129) with same tag
        let bBytes = stride(from: 0, to: B.count, by: 2).map {
            UInt8(B[B.index(B.startIndex, offsetBy: $0)..<B.index(B.startIndex, offsetBy: $0 + 2)], radix: 16)!
        }
        var offset = 0
        while offset < bBytes.count {
            let chunkSize = min(255, bBytes.count - offset)
            data.append(0x03)
            data.append(UInt8(chunkSize))
            data.append(contentsOf: bBytes[offset..<offset + chunkSize])
            offset += chunkSize
        }
        return data.map { String(format: "%02x", $0) }.joined()
    }()

    // MARK: - Tests

    @Test("m1() encodes state=1 and method=pairSetup")
    func m1Encoding() throws {
        let handler = HAPPairSetupHandler(clientIdentifier: Self.clientID)
        let m1 = try handler.m1()
        let tlv = TLV8.decode(m1)
        #expect(tlv[TLVTag.state.rawValue] == Data([1]))
        #expect(tlv[TLVTag.method.rawValue] == Data([0]))
    }

    @Test("m3() produces the expected client proof against a canned M2")
    func m3ProducesExpectedProof() throws {
        let handler = HAPPairSetupHandler(
            clientIdentifier: Self.clientID,
            srpPrivateKey: Self.clientPrivateA
        )
        let m2 = Data(hex: Self.m2TLVHex)
        let m3 = try handler.m3(fromResponse: m2, pin: Self.pin)
        let tlv = TLV8.decode(m3)

        // state should be 3
        #expect(tlv[TLVTag.state.rawValue] == Data([3]))

        // publicKey = A, should match the expected vector from SRPTests
        let expectedAHex =
            "bc0e7cf5dc3babf67dcedbb3b140aacc6cac43f4336b43bbd5de48d6ea7c8eda"
            + "66924e354255225bccad9debe21182e6bb050f3ff3e6cfbb62c229379968c70c"
            + "a436ad649a0b051373184215eef046f6f1f2256838f958581f6c7b2b85fa4afe"
            + "326a0e8a951d4489305331aff88a136fd8d108bcc95fceb7e557c889c828bd23"
            + "fb0702f053e1ca6470fb3c76bce4843fc005c7ea675740f8550212656cfc8919"
            + "d9db805a434a68229e0d9dfe43fc16dc680a5ce74b77cf374353b05759bc1da3"
            + "a9dabde30a4209381c87ca83d9483abdf66b86f9b1cbda9ad82c62712b87ce6f"
            + "b7069b8fc8df344261821a06d0dc5106af76d4245f3f7737a94dbc484b415555"
            + "dc401842d3011204553ba9f611b02bc38de26eba1a76bf8350205a62c436ba1c"
            + "3c7c69d59318bd107fd1c1f5d846b3142e85a5d49e522655e020ed1bfe1e186c"
            + "f923bf328f0b9b4c6a8aa3266ed9125bb98d63827110713be7803122ee4603c5"
            + "4ea31863ce4b10aff31f9073cf63b94733b4f066e72d4ec35687047d5d0db160"
        #expect(tlv[TLVTag.publicKey.rawValue]?.hex == expectedAHex)

        // proof = M1, should match the expected vector
        let expectedM1Hex =
            "30d52aa9136a724c2d3330ef546f263358a771ab0f78843eca9b453a7ee86033"
            + "1fa9f348ae6ba762a87e499d261b235f2c9ae99d697078c8cb5a1e864029da98"
        #expect(tlv[TLVTag.proof.rawValue]?.hex == expectedM1Hex)
    }

    @Test("m3() rejects an M2 response missing the salt")
    func m3RejectsMissingSalt() throws {
        let handler = HAPPairSetupHandler(
            clientIdentifier: Self.clientID,
            srpPrivateKey: Self.clientPrivateA
        )
        // TLV with state=2 but no salt
        let bad = TLV8.encode([
            TLV8.Entry(tag: .state, value: 2),
            TLV8.Entry(tag: .publicKey, data: Data(count: 384)),
        ])
        #expect(throws: ATVError.self) {
            try handler.m3(fromResponse: bad, pin: Self.pin)
        }
    }

    @Test("m3() surfaces a server error TLV as authenticationFailed")
    func m3SurfacesServerError() throws {
        let handler = HAPPairSetupHandler(
            clientIdentifier: Self.clientID,
            srpPrivateKey: Self.clientPrivateA
        )
        // TLV with error=Authentication (0x02)
        let errorTLV = TLV8.encode([
            TLV8.Entry(tag: .state, value: 2),
            TLV8.Entry(tag: .error, value: 0x02),
        ])
        var thrown: ATVError?
        do {
            _ = try handler.m3(fromResponse: errorTLV, pin: Self.pin)
        } catch {
            thrown = error
        }
        guard case .authenticationFailed = thrown else {
            Issue.record("Expected authenticationFailed, got \(String(describing: thrown))")
            return
        }
    }

    @Test("m5() fails if called before m3")
    func m5BeforeM3() throws {
        let handler = HAPPairSetupHandler(clientIdentifier: Self.clientID)
        // Construct a syntactically valid M4
        let m4 = TLV8.encode([
            TLV8.Entry(tag: .state, value: 4),
            TLV8.Entry(tag: .proof, data: Data(count: 64)),
        ])
        #expect(throws: ATVError.self) {
            try handler.m5(fromResponse: m4)
        }
    }

    @Test("finish() fails if called before m5")
    func finishBeforeM5() throws {
        let handler = HAPPairSetupHandler(clientIdentifier: Self.clientID)
        let m6 = TLV8.encode([
            TLV8.Entry(tag: .state, value: 6),
            TLV8.Entry(tag: .encryptedData, data: Data(count: 32)),
        ])
        #expect(throws: ATVError.self) {
            try handler.finish(fromResponse: m6)
        }
    }
}

// Data(hex:) and .hex come from SRPTests.swift in the same target.
