// swift-format-ignore-file: AlwaysUseLowerCamelCase
// SRP fixtures use single-letter uppercase names (A, B, M1, K, M2) to match
// the notation in SRP.swift, RFC 5054, and pyatv's hap_srp.py.

import BigInt
import Foundation
import Testing

@testable import SwiftATV

/// Tests for the SRP-6a client primitives used by HAP pair-setup.
///
/// The canned vectors are generated by running pyatv's srptools dependency
/// directly (pure Python) with fixed inputs. If these tests fail, the Swift
/// `SRPClient` has diverged from what an Apple TV expects on the wire.
///
/// Vector generation script (reproducible):
/// ```python
/// from srptools import SRPContext, SRPClientSession, constants
/// import hashlib
/// ctx = SRPContext(
///     "Pair-Setup", "1234",
///     prime=constants.PRIME_3072,
///     generator=constants.PRIME_3072_GEN,
///     hash_func=hashlib.sha512,
/// )
/// # fixed salt + server B + client private 'a' for determinism
/// ```
@Suite("SRP-6a client (pyatv vectors)")
struct SRPTests {

    // MARK: - Vector: pin=1234, Pair-Setup, 3072-bit group

    private static let clientPrivateA = BigUInt(
        "0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20",
        radix: 16
    )!

    private static let pin = "1234"

    private static let saltHex =
        "830a04e00070c46978c6b05b7c67f545"

    private static let serverPublicBHex =
        "c7f4f55c10d0abbc303dfbbe8ac2b12f2522e3e3d038bc9c196d910c7ad19b76"
        + "da8755093b3f1c3352f6896493b924ba4c4f300721079225dcc0b7ded37750e2"
        + "8e57ccf1a26f09042abb9c087c7f8d48babe1c307fc745244ba71df5289bf359"
        + "ab1ebd135e5af837800bd09e70a0da8fda8e835c9edd52af59981d77d2f323b3"
        + "252d2d5226269685c9af791fe260506222281905c87a2010deda12b528a378d6"
        + "b1df7e0fd51a70ca309c047a48232728beafa91413451974d5ac18bb55fba5a5"
        + "a6bf15f35b161569bab7d7c719a17b937a8e9bbdf273f47006dbcfffa571ad3a"
        + "27e706d860de7e79c264e065aa4b84f0f89c7dc6c1991db7bebc3d86bc7895b4"
        + "2d507e3427385fa247208bc1e3f6444f3915a787470afd743d866f9704bb82c9"
        + "03d94a8b6e2679f2ed1796f125839b63cf261739465f4ff28974fdc343de8b8d"
        + "2a391fb093e6131551409e9e3e1ae76c33b439de1f775a9f7c6e9d72ae319b81"
        + "b2eabaec21e2ba59388f28ca55d9f13d59bb2b5ff68f14ed03ce1dc425683e9a"

    private static let expectedClientPublicAHex =
        "bc0e7cf5dc3babf67dcedbb3b140aacc6cac43f4336b43bbd5de48d6ea7c8eda"
        + "66924e354255225bccad9debe21182e6bb050f3ff3e6cfbb62c229379968c70c"
        + "a436ad649a0b051373184215eef046f6f1f2256838f958581f6c7b2b85fa4afe"
        + "326a0e8a951d4489305331aff88a136fd8d108bcc95fceb7e557c889c828bd23"
        + "fb0702f053e1ca6470fb3c76bce4843fc005c7ea675740f8550212656cfc8919"
        + "d9db805a434a68229e0d9dfe43fc16dc680a5ce74b77cf374353b05759bc1da3"
        + "a9dabde30a4209381c87ca83d9483abdf66b86f9b1cbda9ad82c62712b87ce6f"
        + "b7069b8fc8df344261821a06d0dc5106af76d4245f3f7737a94dbc484b415555"
        + "dc401842d3011204553ba9f611b02bc38de26eba1a76bf8350205a62c436ba1c"
        + "3c7c69d59318bd107fd1c1f5d846b3142e85a5d49e522655e020ed1bfe1e186c"
        + "f923bf328f0b9b4c6a8aa3266ed9125bb98d63827110713be7803122ee4603c5"
        + "4ea31863ce4b10aff31f9073cf63b94733b4f066e72d4ec35687047d5d0db160"

    private static let expectedM1Hex =
        "30d52aa9136a724c2d3330ef546f263358a771ab0f78843eca9b453a7ee86033"
        + "1fa9f348ae6ba762a87e499d261b235f2c9ae99d697078c8cb5a1e864029da98"

    private static let expectedKHex =
        "9f4917a7d080c3f2688a40cf80c1a1db0b4bb1938cb68a18f62aefa353064839"
        + "c7ccfdec067bc3679b89648a9ec594d4631e11d3bd91803aa3132b078e3126c7"

    private static let expectedM2Hex =
        "8fe53b37b22977c676f5f719ff1df5164ee1539a1a3642d989ac135229f6a30a"
        + "760c5dfa54fe71289dc8dfb0340f6681bfb2ca1fcec5a0a87b735d61e2d1e51d"

    // MARK: - Tests

    @Test("Client public key A matches pyatv vector")
    func clientPublicKey() {
        let client = SRPClient(privateKey: Self.clientPrivateA)
        #expect(client.publicKeyA.hex == Self.expectedClientPublicAHex)
    }

    @Test("Client proof M1 and session key K match pyatv vector")
    func clientProofAndSessionKey() throws {
        var client = SRPClient(privateKey: Self.clientPrivateA)
        let (m1, k) = try client.processChallenge(
            salt: Data(hex: Self.saltHex),
            serverPublicB: Data(hex: Self.serverPublicBHex),
            pin: Self.pin
        )
        #expect(m1.hex == Self.expectedM1Hex)
        #expect(k.hex == Self.expectedKHex)
    }

    @Test("Server proof verification accepts correct M2")
    func serverProofCorrect() throws {
        var client = SRPClient(privateKey: Self.clientPrivateA)
        _ = try client.processChallenge(
            salt: Data(hex: Self.saltHex),
            serverPublicB: Data(hex: Self.serverPublicBHex),
            pin: Self.pin
        )
        // Should not throw.
        try client.verifyServerProof(Data(hex: Self.expectedM2Hex))
    }

    @Test("Server proof verification rejects wrong M2")
    func serverProofWrong() throws {
        var client = SRPClient(privateKey: Self.clientPrivateA)
        _ = try client.processChallenge(
            salt: Data(hex: Self.saltHex),
            serverPublicB: Data(hex: Self.serverPublicBHex),
            pin: Self.pin
        )
        var wrong = Data(hex: Self.expectedM2Hex)
        wrong[0] ^= 0xFF
        #expect(throws: ATVError.self) {
            try client.verifyServerProof(wrong)
        }
    }

    @Test("verifyServerProof before processChallenge throws invalidState")
    func serverProofBeforeChallenge() {
        let client = SRPClient(privateKey: Self.clientPrivateA)
        #expect(throws: ATVError.self) {
            try client.verifyServerProof(Data(hex: Self.expectedM2Hex))
        }
    }

    @Test("Zero server public key B is rejected")
    func zeroBRejected() {
        var client = SRPClient(privateKey: Self.clientPrivateA)
        // B == 0 → B mod N == 0 → reject
        let zeroB = Data(count: 384)
        #expect(throws: ATVError.self) {
            try client.processChallenge(salt: Data(hex: Self.saltHex), serverPublicB: zeroB, pin: "1234")
        }
    }
}

// Shared hex helpers live in TestHelpers.swift.
